final schedule = [
  {
    'id': '0',
    'date': '10/24/23',
    'matchup': 'Suns @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '1',
    'date': '10/27/23',
    'matchup': 'Warriors @ Kings',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '2',
    'date': '10/29/23',
    'matchup': 'Warriors @ Rockets',
    'time': '7:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '3',
    'date': '10/30/23',
    'matchup': 'Warriors @ Pelicans',
    'time': '8:00PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '4',
    'date': '11/1/23',
    'matchup': 'Kings @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '5',
    'date': '11/3/23',
    'matchup': 'Warriors @ Thunder',
    'time': '8:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '6',
    'date': '11/5/23',
    'matchup': 'Warriors @ Cavaliers',
    'time': '6:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '7',
    'date': '11/6/23',
    'matchup': 'Warriors @ Pistons',
    'time': '7:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '8',
    'date': '11/8/23',
    'matchup': 'Warriors @ Nuggets',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '9',
    'date': '11/11/23',
    'matchup': 'Cavaliers @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '10',
    'date': '11/12/23',
    'matchup': 'Timberwolves @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '11',
    'date': '11/14/23',
    'matchup': 'Timberwolves @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '12',
    'date': '11/16/23',
    'matchup': 'Thunder @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '13',
    'date': '11/18/23',
    'matchup': 'Thunder @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '14',
    'date': '11/20/23',
    'matchup': 'Rockets @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '15',
    'date': '11/22/23',
    'matchup': 'Warriors @ Suns',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '16',
    'date': '11/24/23',
    'matchup': 'Spurs @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '17',
    'date': '11/28/23',
    'matchup': 'Warriors @ Kings',
    'time': '10:00PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '18',
    'date': '11/30/23',
    'matchup': 'Clippers @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '19',
    'date': '12/2/23',
    'matchup': 'Warriors @ Clippers',
    'time': '4:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '20',
    'date': '12/12/23',
    'matchup': 'Warriors @ Suns',
    'time': '10:00PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '21',
    'date': '12/14/23',
    'matchup': 'Warriors @ Clippers',
    'time': '10:30PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '22',
    'date': '12/16/23',
    'matchup': 'Nets @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '23',
    'date': '12/17/23',
    'matchup': 'Warriors @ Trail Blazers',
    'time': '9:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '24',
    'date': '12/19/23',
    'matchup': 'Celtics @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '25',
    'date': '12/22/23',
    'matchup': 'Wizards @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '26',
    'date': '12/23/23',
    'matchup': 'Trail Blazers @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '27',
    'date': '12/25/23',
    'matchup': 'Warriors @ Nuggets',
    'time': '2:30PM (EST)',
    'channel': 'ABC',
  },
  {
    'id': '28',
    'date': '12/28/23',
    'matchup': 'Heat @ Warriors',
    'time': '10:0PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '29',
    'date': '12/30/23',
    'matchup': 'Mavericks @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '30',
    'date': '1/2/24',
    'matchup': 'Magic @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '31',
    'date': '1/4/24',
    'matchup': 'Nuggets @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '32',
    'date': '1/5/24',
    'matchup': 'Pistons @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '33',
    'date': '1/7/24',
    'matchup': 'Raptors @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '34',
    'date': '1/10/24',
    'matchup': 'Pelicans @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '35',
    'date': '1/12/24',
    'matchup': 'Warriors @ Bulls',
    'time': '8:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '36',
    'date': '1/13/24',
    'matchup': 'Warriors @ Bucks',
    'time': '8:00PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '37',
    'date': '1/15/24',
    'matchup': 'Warriors @ Grizzlies',
    'time': '6:00PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '38',
    'date': '1/17/24',
    'matchup': 'Warriors @ Jazz',
    'time': '9:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '39',
    'date': '1/19/24',
    'matchup': 'Mavericks @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '40',
    'date': '1/24/24',
    'matchup': 'Hawks @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '41',
    'date': '1/25/24',
    'matchup': 'Kings @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '42',
    'date': '1/27/24',
    'matchup': 'Lakers @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'ABC',
  },
  {
    'id': '43',
    'date': '1/30/24',
    'matchup': '76ers @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '44',
    'date': '2/2/24',
    'matchup': 'Warriors @ Grizzlies',
    'time': '8:00PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '45',
    'date': '2/3/24',
    'matchup': 'Warriors @ Hawks',
    'time': '7:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '46',
    'date': '2/5/24',
    'matchup': 'Warriors @ Nets',
    'time': '7:30PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '47',
    'date': '2/7/24',
    'matchup': 'Warriors @ 76ers',
    'time': '7:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '48',
    'date': '2/8/24',
    'matchup': 'Warriors @ Pacers',
    'time': '7:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '49',
    'date': '2/10/24',
    'matchup': 'Suns @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'ABC',
  },
  {
    'id': '50',
    'date': '2/12/24',
    'matchup': 'Warriors @ Jazz',
    'time': '9:00PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '51',
    'date': '2/14/24',
    'matchup': 'Clippers @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '52',
    'date': '2/22/24',
    'matchup': 'Lakers @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '53',
    'date': '2/23/24',
    'matchup': 'Hornets @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '54',
    'date': '2/25/24',
    'matchup': 'Nuggets @ Warriors',
    'time': '7:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '55',
    'date': '2/27/24',
    'matchup': 'Warriors @ Wizards',
    'time': '7:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '56',
    'date': '2/29/24',
    'matchup': 'Warriors @ Knicks',
    'time': '7:30PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '57',
    'date': '3/1/24',
    'matchup': 'Warriors @ Raptors',
    'time': '7:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '58',
    'date': '3/3/24',
    'matchup': 'Warriors @ Celtics',
    'time': '3:30PM (EST)',
    'channel': 'ABC',
  },
  {
    'id': '59',
    'date': '3/6/24',
    'matchup': 'Bucks @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '60',
    'date': '3/7/24',
    'matchup': 'Bulls @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '61',
    'date': '3/9/24',
    'matchup': 'Spurs @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '62',
    'date': '3/11/24',
    'matchup': 'Warriors @ Spurs',
    'time': '8:00PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '63',
    'date': '3/13/24',
    'matchup': 'Warriors @ Mavericks',
    'time': '8:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '64',
    'date': '3/16/24',
    'matchup': 'Warriors @ Lakers',
    'time': '8:30PM (EST)',
    'channel': 'ABC',
  },
  {
    'id': '65',
    'date': '3/18/24',
    'matchup': 'Knicks @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '66',
    'date': '3/20/24',
    'matchup': 'Grizzlies @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'ESPN',
  },
  {
    'id': '67',
    'date': '3/22/24',
    'matchup': 'Pacers @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '68',
    'date': '3/24/24',
    'matchup': 'Warriors @ Timberwolves',
    'time': '7:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '69',
    'date': '3/26/24',
    'matchup': 'Warriors @ Heat',
    'time': '7:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '70',
    'date': '3/27/24',
    'matchup': 'Warriors @ Magic',
    'time': '7:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '71',
    'date': '3/29/24',
    'matchup': 'Warriors @ Hornets',
    'time': '7:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '72',
    'date': '3/31/24',
    'matchup': 'Warriors @ Spurs',
    'time': '7:00PM (EST)',
    'channel': 'NBA TV',
  },
  {
    'id': '73',
    'date': '4/2/24',
    'matchup': 'Warriors @ Mavericks',
    'time': '7:30PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '74',
    'date': '4/4/24',
    'matchup': 'Warriors @ Rockets',
    'time': '8:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '75',
    'date': '4/7/24',
    'matchup': 'Jazz @ Warriors',
    'time': '8:30PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '76',
    'date': '4/9/24',
    'matchup': 'Warriors @ Lakers',
    'time': '10:00PM (EST)',
    'channel': 'TNT',
  },
  {
    'id': '77',
    'date': '4/11/24',
    'matchup': 'Warriors @ Trail Blazers',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '78',
    'date': '4/12/24',
    'matchup': 'Pelicans @ Warriors',
    'time': '10:00PM (EST)',
    'channel': 'Local TV',
  },
  {
    'id': '79',
    'date': '4/14/24',
    'matchup': 'Jazz @ Warriors',
    'time': '3:30PM (EST)',
    'channel': 'Local TV',
  },
];
